[2021-11-21 13:39:43,540] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_data.load_initial_data scheduled__2021-11-20T00:00:00+00:00 [queued]>
[2021-11-21 13:39:43,550] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_data.load_initial_data scheduled__2021-11-20T00:00:00+00:00 [queued]>
[2021-11-21 13:39:43,551] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 13:39:43,551] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-21 13:39:43,551] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 13:39:43,559] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): load_initial_data> on 2021-11-20 00:00:00+00:00
[2021-11-21 13:39:43,562] {standard_task_runner.py:52} INFO - Started process 40284 to run task
[2021-11-21 13:39:43,567] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_data', 'load_initial_data', 'scheduled__2021-11-20T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/etl_job.py', '--cfg-path', '/tmp/tmp21tillgl', '--error-file', '/tmp/tmp0g5jj3ws']
[2021-11-21 13:39:43,567] {standard_task_runner.py:77} INFO - Job 16: Subtask load_initial_data
[2021-11-21 13:39:43,597] {logging_mixin.py:109} INFO - Running <TaskInstance: load_data.load_initial_data scheduled__2021-11-20T00:00:00+00:00 [running]> on host ubuntu2110.linuxvmimages.local
[2021-11-21 13:39:43,623] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_data
AIRFLOW_CTX_TASK_ID=load_initial_data
AIRFLOW_CTX_EXECUTION_DATE=2021-11-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-20T00:00:00+00:00
[2021-11-21 13:39:43,628] {base.py:70} INFO - Using connection to: id: postgres_default. Host: localhost, Port: 5432, Schema: dailydb, Login: postgres, Password: ***, extra: {}
[2021-11-21 13:39:43,654] {dbapi.py:225} INFO - Running statement: INSERT INTO transaction (id, creation_date, sales_value) values (1,'2021-11-20', 1000);, parameters: None
[2021-11-21 13:39:43,656] {dbapi.py:233} INFO - Rows affected: 1
[2021-11-21 13:39:43,664] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=load_data, task_id=load_initial_data, execution_date=20211120T000000, start_date=20211121T063943, end_date=20211121T063943
[2021-11-21 13:39:43,706] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-21 13:39:43,720] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
